relaycorp/awala-endpoint-android

- lib/src/main/java/tech/relaycorp/relaydroid/GatewayClientImpl.kt
- lib/src/main/java/tech/relaycorp/relaydroid/background/ServiceInteractor.kt
- lib/src/test/java/tech/relaycorp/relaydroid/GatewayClientImplTest.kt
Next step will be error handling across the other gateway methods. This one is just focused on bind/unbind.
> chore: Test gateway binding

- lib/src/main/java/tech/relaycorp/relaydroid/endpoint/ThirdPartyEndpoint.kt
- lib/src/test/java/tech/relaycorp/relaydroid/endpoint/PublicThirdPartyEndpointTest.kt
> fix: Public 3rd party endpoints are now looked up by private address

- lib/src/main/java/tech/relaycorp/relaydroid/common/Base64Utils.kt
- lib/src/main/java/tech/relaycorp/relaydroid/endpoint/ThirdPartyEndpoint.kt
- lib/src/main/java/tech/relaycorp/relaydroid/messaging/OutgoingMessage.kt
- lib/src/main/java/tech/relaycorp/relaydroid/storage/StorageImpl.kt
- lib/src/test/java/tech/relaycorp/relaydroid/endpoint/PublicThirdPartyEndpointTest.kt
- lib/src/test/java/tech/relaycorp/relaydroid/messaging/MessageTest.kt
- lib/src/test/java/tech/relaycorp/relaydroid/messaging/OutgoingMessageTest.kt
- lib/src/test/java/tech/relaycorp/relaydroid/test/MessageFactory.kt
- lib/src/test/java/tech/relaycorp/relaydroid/test/ThirdPartyEndpointFactory.kt
> fix: Re-introduce 3rd party public address

- lib/build.gradle
- lib/src/main/java/tech/relaycorp/relaydroid/endpoint/ThirdPartyEndpoint.kt
- lib/src/test/java/tech/relaycorp/relaydroid/endpoint/PublicThirdPartyEndpointTest.kt
> fix: Change to BSON serialization for public 3rd party

- lib/build.gradle
- lib/src/main/java/tech/relaycorp/relaydroid/RelaynetTemp.kt
> fix: Global vars

- lib/src/main/java/tech/relaycorp/relaydroid/endpoint/ThirdPartyEndpoint.kt
- lib/src/test/java/tech/relaycorp/relaydroid/endpoint/PrivateThirdPartyEndpointTest.kt
- lib/src/test/java/tech/relaycorp/relaydroid/endpoint/PublicThirdPartyEndpointTest.kt
- lib/src/test/java/tech/relaycorp/relaydroid/test/ThirdPartyEndpointFactory.kt
> feat: Delete third party endpoint

- lib/src/main/java/tech/relaycorp/awaladroid/messaging/OutgoingMessage.kt
- lib/src/test/java/tech/relaycorp/awaladroid/messaging/OutgoingMessageTest.kt
> fix: Parcel's expiry date should be 6 months

- lib/src/main/java/tech/relaycorp/awaladroid/Awala.kt
- lib/src/test/java/tech/relaycorp/awaladroid/AwalaTest.kt
> feat: Handle setup pending

- README.md
- build.gradle
- lib/build.gradle
> fix: Release to JitPack and get dependencies from Maven Central

- build.gradle
- lib/build.gradle
This regression was introduced in #121.
> fix: Reinstate generation of AAR

- lib/src/main/java/tech/relaycorp/awaladroid/messaging/ReceiveMessages.kt
Fixes https://github.com/relaycorp/relaynet-gateway-android/issues/411
> fix: ReceiveMessages premature client close

- lib/src/main/AndroidManifest.xml
for: https://github.com/relaycorp/relaynet-gateway-android/pull/576
> fix: Rename action name for incoming parcels

- lib/src/main/java/tech/relaycorp/awaladroid/endpoint/ThirdPartyEndpoint.kt
- lib/src/main/java/tech/relaycorp/awaladroid/messaging/IncomingMessage.kt
- lib/src/test/java/tech/relaycorp/awaladroid/endpoint/PrivateThirdPartyEndpointTest.kt
- lib/src/test/java/tech/relaycorp/awaladroid/messaging/IncomingMessageTest.kt
- lib/src/test/java/tech/relaycorp/awaladroid/messaging/StubACK.kt
> feat: Store incoming PDA renewals

- .github/workflows/ci.yml
- lib/jacoco.gradle
closes: https://github.com/relaycorp/awala-endpoint-android/issues/5
I just put it to work, the rules seem a bit too much, maybe its time to add more coverage and lower the rules 😄
> chore(CI): Restore jacocoTestCoverageVerification task

- build.gradle
- lib/build.gradle
- lib/src/main/java/tech/relaycorp/awaladroid/endpoint/FirstPartyEndpoint.kt
Bumps [kotlin](https://github.com/JetBrains/kotlin) 1.7.10 -> 1.8.10
Bumps [awala-jvm](https://github.com/relaycorp/awala-jvm) 1.66.3 -> 1.66.4
Bumps [awala-keystore-file](https://github.com/relaycorp/awala-keystore-file-jvm) 1.6.3 -> 1.6.4
Bumps [awala-poweb](https://github.com/relaycorp/awala-poweb-jvm) 1.5.31 -> 1.5.35
Bumps [awala-jvm-testing](https://github.com/relaycorp/awala-testing-jvm) 1.5.8 -> 1.5.10
> fix(deps): Bump kotlin 1.7.10 -> 1.8.10, awala 1.66.3 -> 1.66.4, awala-keystore-file 1.6.3 -> 1.6.4, poweb 1.5.31 -> 1.5.35

- lib/src/main/java/tech/relaycorp/awaladroid/endpoint/FirstPartyEndpoint.kt
- lib/src/main/java/tech/relaycorp/awaladroid/endpoint/PrivateThirdPartyEndpointData.kt
- lib/src/main/java/tech/relaycorp/awaladroid/endpoint/ThirdPartyEndpoint.kt
- lib/src/main/java/tech/relaycorp/awaladroid/messaging/IncomingMessage.kt
- lib/src/main/java/tech/relaycorp/awaladroid/messaging/OutgoingMessage.kt
- lib/src/test/java/tech/relaycorp/awaladroid/endpoint/FirstPartyEndpointTest.kt
- lib/src/test/java/tech/relaycorp/awaladroid/endpoint/PrivateThirdPartyEndpointTest.kt
- lib/src/test/java/tech/relaycorp/awaladroid/endpoint/PublicThirdPartyEndpointTest.kt
- lib/src/test/java/tech/relaycorp/awaladroid/messaging/IncomingMessageTest.kt
- lib/src/test/java/tech/relaycorp/awaladroid/messaging/OutgoingMessageTest.kt
- lib/src/test/java/tech/relaycorp/awaladroid/storage/StorageImplTest.kt
- lib/src/test/java/tech/relaycorp/awaladroid/test/MockContextTestCase.kt
- lib/src/test/java/tech/relaycorp/awaladroid/test/ThirdPartyEndpointFactory.kt
By specifying the gateway's Internet address in outgoing parcels.
> fix(PrivateThirdPartyEndpoint): Support comms across Internet gateways

- lib/src/main/java/tech/relaycorp/awaladroid/endpoint/ThirdPartyEndpoint.kt
- lib/src/test/java/tech/relaycorp/awaladroid/endpoint/PrivateThirdPartyEndpointTest.kt
Instead of having to specify the params individually.
> fix(PrivateThirdPartyEndpoint): Import with conn params file

- lib/src/main/java/tech/relaycorp/awaladroid/GatewayClientImpl.kt
- lib/src/test/java/tech/relaycorp/awaladroid/GatewayClientImplTest.kt
> fix: Concurrent messages received

- lib/src/main/java/tech/relaycorp/awaladroid/Awala.kt
- lib/src/main/java/tech/relaycorp/awaladroid/background/GatewayCertificateChangeBroadcastReceiver.kt
- lib/src/main/java/tech/relaycorp/awaladroid/background/IncomingParcelBroadcastReceiver.kt
- lib/src/test/java/tech/relaycorp/awaladroid/AwalaTest.kt
- lib/src/test/java/tech/relaycorp/awaladroid/test/AwalaContextUnits.kt
> fix: Receivers should await setup

- lib/src/main/java/tech/relaycorp/awaladroid/Awala.kt
- lib/src/main/java/tech/relaycorp/awaladroid/GatewayClientImpl.kt
- lib/src/main/java/tech/relaycorp/awaladroid/endpoint/FirstPartyEndpoint.kt
- lib/src/main/java/tech/relaycorp/awaladroid/endpoint/HandleGatewayCertificateChange.kt
- lib/src/main/java/tech/relaycorp/awaladroid/endpoint/RenewExpiringCertificates.kt
- lib/src/test/java/tech/relaycorp/awaladroid/GatewayClientImplTest.kt
> feat: Throw `GatewayUnregisteredException` when gateway is not registered

- lib/build.gradle
- lib/jacoco.gradle
- lib/src/main/java/tech/relaycorp/awaladroid/GatewayClientImpl.kt
- lib/src/test/java/tech/relaycorp/awaladroid/GatewayClientImplTest.kt
Addresses https://github.com/relaycorp/relaynet-gateway-android/issues/724
> feat: Switch to bindAutomatically for the GatewayClient
